// Code generated by gsvc 0.1.0; DO NOT EDIT.

package app

import (
	"example.com/greeter/internal/platform/fault"
	"strings"
)

type GreetPersonInput struct {
	Name string `json:"name"`
}
type GreetPersonOutput struct {
	Message string `json:"message"`
}

func (in GreetPersonInput) Validate() error {

	if strings.TrimSpace(in.Name) == "" {
		return fault.New(fault.Invalid, "name is required")
	}

	return nil
}
