// Code generated by gsvc 0.1.0; DO NOT EDIT.

package httpx

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestDecodeJSON(t *testing.T) {
	type Input struct {
		Amount  string `json:"amount"`
		Enabled bool   `json:"enabled"`
		Count   int64  `json:"count"`
	}
	for _, tc := range []struct {
		name, body string
		ok         bool
	}{
		{"valid zero", `{"amount":"1.23","enabled":false,"count":0}`, true},
		{"missing", `{"amount":"1"}`, false},
		{"unknown", `{"amount":"1","enabled":false,"count":0,"tenant_id":"evil"}`, false},
		{"case alias", `{"amount":"1","Amount":"2","enabled":false,"count":0}`, false},
		{"duplicate", `{"amount":"1","amount":"2","enabled":false,"count":0}`, false},
		{"null", `{"amount":null,"enabled":false,"count":0}`, false},
		{"two documents", `{"amount":"1","enabled":false,"count":0}{}`, false},
		{"array", `[]`, false},
		{"large", `{"amount":"` + strings.Repeat("a", MaxBodyBytes) + `","enabled":false,"count":0}`, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r := httptest.NewRequest(http.MethodPost, "/", strings.NewReader(tc.body))
			r.Header.Set("Content-Type", "application/json")
			var in Input
			err := DecodeJSON(httptest.NewRecorder(), r, &in, "amount", "enabled", "count")
			if (err == nil) != tc.ok {
				t.Fatalf("error=%v, expected success %v", err, tc.ok)
			}
		})
	}
}
func TestContentTypeRequired(t *testing.T) {
	var in struct{}
	r := httptest.NewRequest("POST", "/", strings.NewReader(`{}`))
	if DecodeJSON(httptest.NewRecorder(), r, &in) == nil {
		t.Fatal("missing content type accepted")
	}
}
func TestErrorDoesNotLeak(t *testing.T) {
	w := httptest.NewRecorder()
	Failure(w, errors.New("database password=secret"))
	if w.Code != 500 || strings.Contains(w.Body.String(), "secret") {
		t.Fatal(w.Body.String())
	}
}
func TestQuery(t *testing.T) {
	for _, raw := range []string{"x=1&x=2", "unexpected=1", "x=%zz"} {
		r := httptest.NewRequest("GET", "/", nil)
		r.URL.RawQuery = raw
		if _, err := Query(r, "x"); err == nil {
			t.Fatal(raw)
		}
	}
}
func TestPanicRecovery(t *testing.T) {
	h := Recover(http.HandlerFunc(func(http.ResponseWriter, *http.Request) { panic("secret") }))
	w := httptest.NewRecorder()
	h.ServeHTTP(w, httptest.NewRequest("GET", "/", nil))
	if w.Code != 500 || strings.Contains(w.Body.String(), "secret") {
		t.Fatal(w)
	}
}
