// Code generated by gsvc 0.1.0; DO NOT EDIT.

package fault

import (
	"fmt"
	"testing"
)

func TestWrappedKind(t *testing.T) {
	err := fmt.Errorf("operation: %w", New(Conflict, "already exists"))
	if !IsKind(err, Conflict) {
		t.Fatal("lost kind")
	}
	if IsKind(err, NotFound) {
		t.Fatal("wrong kind")
	}
}
