// Code generated by gsvc 0.1.0; DO NOT EDIT.

package bootstrap

import (
	"example.com/greeter/internal/greetings"
	"example.com/greeter/internal/platform/httpx"
	"net/http"
)

type Dependencies struct {
	Greetings greetings.Dependencies
}

func NewHandler(deps Dependencies) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		httpx.JSON(w, http.StatusOK, map[string]string{"status": "ok"})
	})
	greetings.Register(mux, deps.Greetings)

	return httpx.Recover(mux)
}
