// Code generated by gsvc 0.2.0; DO NOT EDIT.

package bootstrap

import (
	"net/http/httptest"
	"testing"
)

func TestHealth(t *testing.T) {
	w := httptest.NewRecorder()
	NewHandler(Dependencies{}).ServeHTTP(w, httptest.NewRequest("GET", "/healthz", nil))
	if w.Code != 200 {
		t.Fatalf("health status=%d", w.Code)
	}
}
