// Code generated by gsvc 0.2.0; DO NOT EDIT.

package greetings

import (
	"example.com/greeter/internal/greetings/internal/adapter/httpapi"
	"example.com/greeter/internal/greetings/internal/app"
	"net/http"
)

type GreetPersonDeps = app.GreetPersonDeps

type Dependencies struct {
	GreetPerson GreetPersonDeps
}

func Register(mux *http.ServeMux, deps Dependencies) {
	httpapi.Register(mux, httpapi.Handlers{
		GreetPerson: app.NewGreetPerson(deps.GreetPerson),
	})
}
