// Code generated by gsvc 0.2.0; DO NOT EDIT.

package httpapi

import (
	"context"
	"example.com/greeter/internal/greetings/internal/app"
	"example.com/greeter/internal/platform/httpx"
	"net/http"
)

type GreetPersonRunner interface {
	Execute(context.Context, app.GreetPersonInput) (app.GreetPersonOutput, error)
}

type Handlers struct {
	GreetPerson GreetPersonRunner
}

func Register(mux *http.ServeMux, h Handlers) {
	mux.HandleFunc("GET /greetings/{name}", func(w http.ResponseWriter, r *http.Request) {
		var input app.GreetPersonInput

		q, err := httpx.Query(r)
		if err != nil {
			httpx.Failure(w, err)
			return
		}
		_ = q
		input.Name = r.PathValue("name")

		if err := input.Validate(); err != nil {
			httpx.Failure(w, err)
			return
		}
		output, err := h.GreetPerson.Execute(r.Context(), input)
		if err != nil {
			httpx.Failure(w, err)
			return
		}
		httpx.JSON(w, http.StatusOK, output)
	})

}
