// Code generated by gsvc 0.2.0; DO NOT EDIT.

package httpapi

import (
	"context"
	"example.com/greeter/internal/greetings/internal/app"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

type fakeGreetPerson struct {
	called bool
	input  app.GreetPersonInput
}

func (f *fakeGreetPerson) Execute(_ context.Context, in app.GreetPersonInput) (app.GreetPersonOutput, error) {
	f.called = true
	f.input = in
	return app.GreetPersonOutput{}, nil
}
func TestGreetPersonBinding(t *testing.T) {
	fake := &fakeGreetPerson{}
	mux := http.NewServeMux()
	Register(mux, Handlers{GreetPerson: fake})
	r := httptest.NewRequest("GET", "/greetings/value", strings.NewReader(""))
	r.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, r)
	if w.Code != 200 || !fake.called {
		t.Fatalf("status=%d body=%s called=%v", w.Code, w.Body.String(), fake.called)
	}
	if fake.input.Name != "value" {
		t.Errorf("field name was not bound")
	}

}
