// Package generate renders the versioned service model deterministically. Files
// are formatted before they reach the writer; no user templates or shell execute.
package generate

import (
	"bytes"
	"embed"
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"net/url"
	"strconv"
	"strings"
	"text/template"

	"gsvc.local/cli/internal/assets"
	"gsvc.local/cli/internal/project"
)

//go:embed templates
var templates embed.FS

type data struct {
	Project    project.Manifest
	Module     project.Module
	Operation  project.Operation
	Capability project.CapabilityDefinition
	Version    string
}

const header = "// Code generated by gsvc " + project.Version + "; DO NOT EDIT.\n\n"

func Endpoints(m project.Module) []project.Operation {
	out := []project.Operation{}
	for _, op := range m.Operations {
		if op.Endpoint != nil {
			out = append(out, op)
		}
	}
	return out
}
func pathField(op project.Operation, f project.Field) bool {
	return strings.Contains(op.Endpoint.Path, "{"+f.Name+"}")
}
func queryFields(op project.Operation) []project.Field {
	out := []project.Field{}
	for _, f := range op.Input {
		if !pathField(op, f) {
			out = append(out, f)
		}
	}
	return out
}
func hasType(fields []project.Field, t string) bool {
	for _, f := range fields {
		if f.Type == t {
			return true
		}
	}
	return false
}
func bindQuery(op project.Operation) string {
	var b strings.Builder
	for _, f := range op.Input {
		if pathField(op, f) {
			fmt.Fprintf(&b, "input.%s = r.PathValue(%q)\n", project.Export(f.Name), f.Name)
			continue
		}
		fn := "String"
		if f.Type == "int64" {
			fn = "Int64"
		}
		if f.Type == "bool" {
			fn = "Bool"
		}
		fmt.Fprintf(&b, "input.%s, err = httpx.%s(q, %q)\nif err != nil { httpx.Failure(w, err); return }\n", project.Export(f.Name), fn, f.Name)
	}
	return b.String()
}
func sample(f project.Field) any {
	switch f.Type {
	case "money":
		return "1.25"
	case "int64":
		return int64(42)
	case "bool":
		return true
	default:
		return "value"
	}
}
func sampleBody(op project.Operation) string {
	if op.Kind == "query" {
		return ""
	}
	m := map[string]any{}
	for _, f := range op.Input {
		m[f.Name] = sample(f)
	}
	b, _ := json.Marshal(m)
	return string(b)
}
func sampleURL(op project.Operation) string {
	p := op.Endpoint.Path
	if op.Kind != "query" {
		return p
	}
	q := url.Values{}
	for _, f := range op.Input {
		v := fmt.Sprint(sample(f))
		if pathField(op, f) {
			p = strings.ReplaceAll(p, "{"+f.Name+"}", v)
		} else {
			q.Set(f.Name, v)
		}
	}
	if len(q) > 0 {
		p += "?" + q.Encode()
	}
	return p
}
func sampleGo(f project.Field) string {
	if s, ok := sample(f).(string); ok {
		return strconv.Quote(s)
	}
	return fmt.Sprint(sample(f))
}

func Render(m project.Manifest) (project.Files, error) {
	project.Normalize(&m)
	if err := project.Validate(m); err != nil {
		return nil, err
	}
	out := project.Files{}
	add := func(path, owner string, b []byte) error {
		if strings.HasSuffix(path, ".go") {
			if owner == "generated" {
				b = append([]byte(header), b...)
			}
			formatted, err := format.Source(b)
			if err != nil {
				return fmt.Errorf("format %s: %w\n%s", path, err, b)
			}
			b = formatted
		}
		if _, exists := out[path]; exists {
			return fmt.Errorf("duplicate generated path: %s", path)
		}
		out[path] = project.File{Owner: owner, Content: b}
		return nil
	}
	funcMap := template.FuncMap{"export": project.Export, "gotype": project.GoType, "endpoints": Endpoints, "hastype": hasType, "validatable": func(f []project.Field) bool { return hasType(f, "string") || hasType(f, "money") }, "queryfields": queryFields, "bindquery": bindQuery, "quote": strconv.Quote, "samplebody": sampleBody, "sampleurl": sampleURL, "samplego": sampleGo}
	render := func(path, owner, name string, d data) error {
		text, err := templates.ReadFile("templates/" + name + ".tmpl")
		if err != nil {
			return err
		}
		t, err := template.New(name).Funcs(funcMap).Parse(string(text))
		if err != nil {
			return err
		}
		var b bytes.Buffer
		if err = t.Execute(&b, d); err != nil {
			return err
		}
		return add(path, owner, b.Bytes())
	}
	d := data{Project: m, Version: project.Version}
	for _, f := range []struct{ p, o, t string }{
		{"cmd/api/main.go", "developer", "main.go"}, {"internal/bootstrap/wire.go", "developer", "wire.go"},
		{"internal/bootstrap/routes_gen.go", "generated", "bootstrap.go"}, {"internal/bootstrap/routes_gen_test.go", "generated", "bootstrap_test.go"},
		{"README.md", "developer", "service_readme.md"}, {"AGENTS.md", "generated", "AGENTS.md"},
	} {
		if err := render(f.p, f.o, f.t, d); err != nil {
			return nil, err
		}
	}
	for _, f := range []struct{ p, o, s string }{
		{"go.mod", "developer", "module " + m.GoModule + "\n\ngo 1.23.0\n"},
		{".gitignore", "developer", "/bin/\n.env\n.gsvc/write.lock\n.gsvc/transaction.json\n.gsvc-write-*\n"},
		{"Makefile", "developer", ".PHONY: run test check verify\nrun:\n\tgo run ./cmd/api\ntest:\n\tgo test ./...\ncheck:\n\tgsvc check\nverify:\n\tgsvc check --verify --strict\n"},
		{"CLAUDE.md", "generated", "Read AGENTS.md before editing. Run gsvc contract --json, gsvc inspect --json, and gsvc check --json. Do not hand-edit CLI-owned files.\n"},
	} {
		if err := add(f.p, f.o, []byte(f.s)); err != nil {
			return nil, err
		}
	}
	err := fs.WalkDir(assets.Runtime, "runtime", func(p string, e fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if e.IsDir() {
			return nil
		}
		b, err := assets.Runtime.ReadFile(p)
		if err != nil {
			return err
		}
		b = bytes.ReplaceAll(b, []byte("gsvc.local/cli/internal/assets/runtime/"), []byte(m.GoModule+"/internal/platform/"))
		return add("internal/platform/"+strings.TrimPrefix(p, "runtime/"), "generated", b)
	})
	if err != nil {
		return nil, err
	}
	for _, capability := range m.Capabilities {
		definition, ok := project.CapabilityByID(capability.ID)
		if !ok {
			return nil, fmt.Errorf("validated capability is missing from catalog: %s", capability.ID)
		}
		d.Capability = definition
		for _, output := range definition.Outputs {
			if err = render(output.Path, "generated", output.Template, d); err != nil {
				return nil, err
			}
		}
	}
	for _, mod := range m.Modules {
		d.Module = mod
		root := "internal/" + mod.Name + "/"
		if err = render(root+"module.go", "developer", "module.go", d); err != nil {
			return nil, err
		}
		if err = render(root+"module_gen.go", "generated", "module_gen.go", d); err != nil {
			return nil, err
		}
		for _, pkg := range []string{"app", "domain", "adapter/postgres"} {
			parts := strings.Split(pkg, "/")
			s := "// Package " + parts[len(parts)-1] + " contains this module's " + pkg + " code.\npackage " + parts[len(parts)-1] + "\n"
			if err = add(root+"internal/"+pkg+"/doc.go", "developer", []byte(s)); err != nil {
				return nil, err
			}
		}
		for _, op := range mod.Operations {
			d.Operation = op
			stem := root + "internal/app/" + project.Stem(op.Name)
			if err = render(stem+".go", "developer", "operation.go", d); err != nil {
				return nil, err
			}
			if err = render(stem+"_test.go", "developer", "operation_test.go", d); err != nil {
				return nil, err
			}
			if err = render(stem+"_contract_gen.go", "generated", "contract.go", d); err != nil {
				return nil, err
			}
		}
		if len(Endpoints(mod)) > 0 {
			if err = render(root+"internal/adapter/httpapi/routes_gen.go", "generated", "httpapi.go", d); err != nil {
				return nil, err
			}
			if err = render(root+"internal/adapter/httpapi/routes_gen_test.go", "generated", "httpapi_test.go", d); err != nil {
				return nil, err
			}
		}
	}
	return out, nil
}
